#! /usr/bin/perl
$num_args = $#ARGV + 1;

($name,$passwd,$uid,$gid,$quota,$comment,$gcos,$dir,$shell,$expire)=getpwuid($<);

$pword=$ARGV[0];
$epword=$ENV{'GRIDFTP_PASSWD'};

$salt=join '', ('.', '/', 0..9, 'A'..'Z', 'a'..'z')[rand 64, rand 64];

# if password not supplied as first argument 
# then check if passwd is env variable GRIDFTP_PASSWD
# else prompt for passwd.
if($num_args != 1)
{
	if($epword eq "")
	{
		system "stty -echo";
		print STDERR "Password: ";
		chomp($pword = <STDIN>);
		print "\n";
		system "stty echo";
	} else
	{
		$pword = $epword;
	}
}
$hash=crypt($pword, $salt);
print "$name:$hash:$uid:$gid:$gcos:$dir:$shell\n"
